"""add update timestamp for posts

Revision ID: 0a8a88afe7ef
Revises: 6eddb78a850c
Create Date: 2021-01-10 18:47:21.834316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8a88afe7ef'
down_revision = '6eddb78a850c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('updated_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_updated_timestamp'), 'post', ['updated_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_updated_timestamp'), table_name='post')
    op.drop_column('post', 'updated_timestamp')
    # ### end Alembic commands ###
